version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-logs-volume:/var/log/nginx

    depends_on:
      - service1
      - service2
  service1:
    build: ./service_1
    ports:
      - "8001:8001"
    healthcheck:
      test: ['CMD','curl','-f','http://localhost:8001/health']
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always
  service2:
    build: ./service_2
    ports:
      - "8002:8002"
    healthcheck:
      test: ['CMD','curl','-f','http://localhost:8002/health']
      interval: 10s
      timeout: 3s
      retries: 3
    restart: always  

